[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200

remappings = [
  '@chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip/'
]

fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
base-sepolia = "https://sepolia.base.org"
ronin-saigon = "https://saigon-archive.roninchain.com/rpc"

[etherscan]
base-sepolia = { key = "${BASESCAN_API_KEY}", chain = 42161, url = "https://api-sepolia.basescan.org/api" }

[profile.ronin]
evm_version = "london"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
